#! /usr/bin/env python
# -*- coding:utf-8 -*-
"""
@Time    : 2026/7/120:08
@Author  :shlongqishi@gmail.com
@File    :pytest.ini.py
"""
[pytest]
# 设置缓存文件到指定的地址
cache_dir = tmp/.pytest_cache

# 设置默认的命令行选项
adopts = -v -s
