"""empty message

Revision ID: a5672b35f6e3
Revises: 6421926dd12d
Create Date: 2026-07-06 11:34:20.346071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5672b35f6e3'
down_revision = '6421926dd12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
